// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer Vite env vars (VITE_*) when available. Fall back to NEXT_PUBLIC_* for compatibility
// and finally to the embedded defaults. Using env vars makes it easier to change
// origins for local development (important for CORS checks).
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? import.meta.env.NEXT_PUBLIC_SUPABASE_URL ?? "https://ymsbgrzedjmknowsbpuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "sb_publishable_g6voqGj8zJPrgSGkl2WqOg_WKdL10rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // This should only happen in misconfigured environments. Log details to help debug.
  // eslint-disable-next-line no-console
  console.warn('Supabase config: missing URL or key. SUPABASE_URL=', SUPABASE_URL, 'KEY_PRESENT=', Boolean(SUPABASE_PUBLISHABLE_KEY));
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});